image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository
    - target/

build90:
  stage: build
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf90 $MAVEN_CLI_OPTS install'
    
build91:
  stage: build
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf91 $MAVEN_CLI_OPTS install'
    
build92:
  stage: build
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf92 $MAVEN_CLI_OPTS install'
    
build93:
  stage: build
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf93 $MAVEN_CLI_OPTS install'
    
deploy90:
  stage: deploy
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf90 $MAVEN_CLI_OPTS deploy'
  only:
    - master
    
deploy91:
  stage: deploy
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf91 $MAVEN_CLI_OPTS deploy'
  only:
    - master
    
deploy92:
  stage: deploy
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf92 $MAVEN_CLI_OPTS deploy'
  only:
    - master
    
deploy93:
  stage: deploy
  tags: 
    - DOCKER
  script:
    - 'mvn -P wf93 $MAVEN_CLI_OPTS deploy'
  only:
    - master 

  

